wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1637609667
    t:
      1:
      - 1
      - 2
      - 3
      2:
      - 1
      - 2
      - 3
      3:
      - 16
      4: 3.8.12
      5: 0.12.6
      8:
      - 5
algorithm:
  desc: null
  value: DQN
